In [1]:
import sys

!$sys.executable -m pip install tensorflow

import tensorflow as tf
print("TensorFlow version:", tf.__version__)

from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model


print("dies")


  Using cached libclang-15.0.6.1-py2.py3-none-macosx_10_9_x86_64.whl (25.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 980.4/980.4 kB 6.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 20.0 MB/s eta 0:00:0000:0100:01
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:


      Successfully uninstalled protobuf-3.20.3


2023-02-11 22:05:27.744610: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


TensorFlow version: 2.10.0
dies


In [13]:
import pandas as pd

!$sys.executable -m pip install scikit-learn
!$sys.executable -m pip install keras

from sklearn import preprocessing

df = pd.read_csv('housepricedata.csv')
dataset = df.values

X = dataset[:,0:10]
Y = dataset[:,10]


min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X_scale, Y, test_size=0.3)

X_val, X_test, Y_val, Y_test = train_test_split(X_val_and_test, Y_val_and_test, test_size=0.5)

print(X_train.shape, X_val.shape, X_test.shape, Y_train.shape, Y_val.shape, Y_test.shape)

(1022, 10) (219, 10) (219, 10) (1022,) (219,) (219,)


In [31]:
#Kot: added some imports
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras import regularizers

model_3 = Sequential([
    Dense(1000, activation='relu', kernel_regularizer=regularizers.l2(0.01), input_shape=(10,)),
    Dropout(0.3),
    Dense(1000, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
    Dropout(0.3),
    Dense(1000, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
    Dropout(0.3),
    Dense(1000, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
    Dropout(0.3),
    Dense(1, activation='sigmoid', kernel_regularizer=regularizers.l2(0.01)),
])

model_3.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

hist_3 = model_3.fit(X_train, Y_train,
          batch_size=32, epochs=100)

Epoch 1/100
32/32 [==============================] - 1s 8ms/step - loss: 14.2372 - accuracy: 0.6360
Epoch 2/100
32/32 [==============================] - 0s 7ms/step - loss: 1.7031 - accuracy: 0.8023
Epoch 3/100
32/32 [==============================] - 0s 7ms/step - loss: 0.5572 - accuracy: 0.8571
Epoch 4/100
32/32 [==============================] - 0s 7ms/step - loss: 0.4873 - accuracy: 0.8787
Epoch 5/100
32/32 [==============================] - 0s 7ms/step - loss: 0.4871 - accuracy: 0.8679
Epoch 6/100
32/32 [==============================] - 0s 7ms/step - loss: 0.4875 - accuracy: 0.8748
Epoch 7/100
32/32 [==============================] - 0s 7ms/step - loss: 0.4587 - accuracy: 0.8806
Epoch 8/100
32/32 [==============================] - 0s 7ms/step - loss: 0.4526 - accuracy: 0.8933
Epoch 9/100
32/32 [==============================] - 0s 7ms/step - loss: 0.4657 - accuracy: 0.8777
Epoch 10/100
32/32 [==============================] - 0s 7ms/step - loss: 0.4399 - accuracy: 0.8924
Epoch 11

32/32 [==============================] - 0s 7ms/step - loss: 0.4157 - accuracy: 0.8933
Epoch 84/100
32/32 [==============================] - 0s 7ms/step - loss: 0.4336 - accuracy: 0.8914
Epoch 85/100
32/32 [==============================] - 0s 7ms/step - loss: 0.4355 - accuracy: 0.8796
Epoch 86/100
32/32 [==============================] - 0s 7ms/step - loss: 0.4419 - accuracy: 0.8826
Epoch 87/100
32/32 [==============================] - 0s 7ms/step - loss: 0.4192 - accuracy: 0.8836
Epoch 88/100
32/32 [==============================] - 0s 7ms/step - loss: 0.4130 - accuracy: 0.8963
Epoch 89/100
32/32 [==============================] - 0s 7ms/step - loss: 0.4191 - accuracy: 0.8953
Epoch 90/100
32/32 [==============================] - 0s 7ms/step - loss: 0.4330 - accuracy: 0.8836
Epoch 91/100
32/32 [==============================] - 0s 7ms/step - loss: 0.4179 - accuracy: 0.8904
Epoch 92/100
32/32 [==============================] - 0s 7ms/step - loss: 0.4232 - accuracy: 0.8865
Epoch 93/100


In [14]:
#Kot: Already installed it at the top

pip install tensorflow


Note: you may need to restart the kernel to use updated packages.


In [33]:
test_input = dataset[:,0:10]
print(test_input)


prediction = model_3.predict(X_test[:1])

print(prediction)

[[ 8450     7     5 ...     8     0   548]
 [ 9600     6     8 ...     6     1   460]
 [11250     7     5 ...     6     1   608]
 ...
 [ 9042     7     9 ...     9     2   252]
 [ 9717     5     6 ...     5     0   240]
 [ 9937     5     6 ...     6     0   276]]
1/1 [==============================] - 0s 16ms/step
[[0.05441342]]
